//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen_DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despachos
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string TipoDeAccion { get; set; }
        public long IdCliente { get; set; }
        public string Contacto { get; set; }
        public string DetalleDeProductos { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
